layout_spectrum: 0.6135603
typography_spectrum: 0.244446
color:
  saturation: 0.9292908
  lightness: 0.8374647
  brandStrength: 0.9013727
  rhythmicContrast: 0.8050949
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Amanda Valentina
